version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sr-health-backend
    container_name: sr-health-app
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - sr-health-network

  mysql:
    image: mysql:8.0
    container_name: sr-health-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: srhealth
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - sr-health-dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=256M --innodb_buffer_pool_size=512M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - sr-health-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: sr-health-pma
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - sr-health-network

networks:
  sr-health-network:
    driver: bridge

volumes:
  sr-health-dbdata:
    driver: local
